### ISSUE TITLE
Keybindings do not work with steam in-home streaming

### ISSUE THREAD

**Issue by EE-GSlomin** [Gerry1135/MemGraph#2]
Unfortunately I cannot use the mod+end/home/etc. keys with steam in-home streaming. Would it be possible to allow the keybindings to be reconfigured with an external file or an in-game menu?

Currently I am running the game on my windows desktop and streaming it to my macbook pro on the local network. The OSX key combination (FN+left/right arrow) does not seem to register through steam.

**Comment by Gerry1135** [comment]
Configurable key bindings are planned, I just need to find some spare time to do it.

**Comment by Gerry1135** [comment]
Version 1.0.0.9 with configurable keybindings (and other features for ease of heap padding use) is now available.
