### ISSUE TITLE
"Reload Database" Causes GUI to be duplicated

### ISSUE THREAD

**Issue by gomker** [Gerry1135/MemGraph#3]
I do part modifications and I recently found out about Alt+F12, database - > Reload database (late to the game, I know)
I find it duplicates the GUI window, and if I had one hidden before, it will hide the 2nd and show the first. 
Reload again, now I have 3 etc...

**Comment by Gerry1135** [comment]
Hmm, that's a bit weird, it's supposed to only ever get started once. Must be a quirk of how the reload works. I'm away from home at the moment but I'll take a look to see if there's a handy GameEvent I can hook into when I get back.

**Comment by gomker** [comment]
I believe this will load Assemblies too, which is nice for part mod testing - have not verified, but it looks as if MemGraph is starting for the first time like game load.

**Comment by Gerry1135** [comment]
Yeah, if there isn't a GameEvent then I should just be able to make it a singleton and make any new instances just kill themselves.

**Comment by Gerry1135** [comment]
Fixed in f9a3e8e8c4d461df15a4ca4321717e5bc06a95db
Version 1.1.0.3
